server:
  port: 8089
  servlet:
    context-path:

spring:
  messages:
    encoding: UTF-8
    basename: message/messages

  profiles:
    active: dev, value

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/mvc1
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
